packages:
  - apps/*
  - packages/*
  - firebase/functions

allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  protobufjs: true
  re2: true

minimumReleaseAgeExclude:
  - react-native-iap@15.4.1
