// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as IndexRoute } from '../pages';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof IndexRoute)['_outputType'];
  }
}
